str=input()
str=str.replace('T', 't')
str=str.replace('A', 'a')
str=str.replace('t', 'A')
str=str.replace('a', 'T')
str=str.replace('G', 'g')
str=str.replace('C', 'c')
str=str.replace('g', 'C')
str=str.replace('c', 'G')
print(str[::-1])
